version: 1.0.{build}

image: Visual Studio 2015

pull_requests:  
  do_not_increment_build_number: true

init:  
  - ps: |
      if (-not ($env:PowershellVersion)) {$env:PowershellVersion = "5.1"}
      if (([version]$env:PowershellVersion).Major -ge 6) {$env:posh = "pwsh"} else {$env:posh = "powershell"}
      Add-Content (Join-Path $Home ".git-credentials") "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global credential.helper "store --file ~/.git-credentials"
  - git config --global user.email "[email blocked]"
  - git config --global user.name "AtlassianPS automation"

install:  
  - ps: '& $env:posh -File "./Tools/setup.ps1"'

build_script:  
  - ps: '& $env:posh -Command "Invoke-Build"'
  # This performs the following actions:
  #  - build source
  #  - run tests against result of build
  #  - creates a zip from release
  #  - create nupkg for deployment

artifacts:  
  - path: '**\*.nupkg'
  - path: '**\*.zip'

before_deploy:  
  # Test if this should deploy
  #     we don't want to deploy anything that is not on master
  - ps: '& $env:posh -Command "Should this deploy??"'

deploy:  
  - provider: NuGet
    server: https://my.nuget.server/feed
    api_key:
      secure: FYWX6NfjZIVw==
    skip_symbols: false
    symbol_server: https://your.symbol.server/feed
    artifact: MyPackage.nupkg

  - provider: GitHub
    artifact: /.*\.zip/
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true
<pre><code>
I want `deploy` only to be executed when on branch `master`.
I would write a PS script in `before_deploy` to test this.
But what kind of code would `before_deploy` have to execute to skip `deploy` without failing the build job?

How can I make the `artifacts` dependent on how the branch?
My goal is to set this up so that nothing apart from `master` can be deployed</code>
</pre>